openapi: 3.0.0
info:
  title: Documentation for FinApp
  description: REST API documentation
  contact:
    name: Boburmirzo Kozimov
    email: bobur.kozimov@gmail.com
  version: 1.0.0
servers:
  - url: /api
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login to your account
      description: Use this route to login your page once the client has been registered
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              properties:
                '':
                  properties:
                    uuid:
                      type: string
                    auth_key:
                      type: string
                  type: object
              example:
                uuid: '998901234567'
                auth_key: auth_key_example
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                type: object
  /refresh:
    post:
      tags:
        - Auth
      summary: refresh token
      description: refresh token
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              properties:
                '':
                  properties:
                    uuid:
                      type: string
                    refresh_token:
                      type: string
                  type: object
              type: object
              example:
                uuid: something
                refresh_token: your_refresh_token
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        access_token:
                          type: string
                        refresh_token:
                          type: string
                      type: object
                type: object
  /me:
    get:
      tags:
        - Auth
      summary: Personal info
      operationId: me
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  client_id:
                    type: string
                  status:
                    type: boolean
                  balance:
                    type: string
                  phone:
                    type: string
                  cards:
                    type: array
                    items:
                      properties:
                        id:
                          type: string
                        balance:
                          type: string
                      type: object
                  card_transactions:
                    type: array
                    items:
                      properties:
                        id:
                          type: string
                        sum:
                          type: string
                      type: object
                type: object
        '401':
          description: Unauthenticated
      security:
        - api_key_security_example: [ ]
  /chat:
    post:
      tags:
        - Chat
      summary: To send a message,first of you need to create a chat room
      description: To send a message in a chat room
      operationId: Chat
      requestBody:
        content:
          application/json:
            schema:
              properties:
                '':
                  properties:
                    message:
                      type: string
                    chat_room_id:
                      type: string
                  type: object
              type: object
              example:
                message: Hello
                chat_room_id: '1'
      responses:
        '200':
          description: Success
      security:
        - api_key_security_example: [ ]
  /chat-room:
    post:
      tags:
        - Chat
      summary: Createing Chat Room
      description: To create a chat room
      operationId: ChatRoom
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        chat_room_id:
                          type: string
                      type: object
                type: object
      security:
        - api_key_security_example: [ ]
  /help-request:
    post:
      tags:
        - Help
      summary: Get help from operator
      description: Get help from operator
      operationId: help
      requestBody:
        content:
          application/json:
            schema:
              properties:
                '':
                  properties:
                    phone:
                      type: string
                    name:
                      type: string
                    preferred_language:
                      type: string
                    messenger_type:
                      type: string
                  type: object
              type: object
              example:
                phone: '998901234567'
                name: Boburmirzo Kozimov
                preferred_language: ENGLISH
                messenger_type: TELEGRAM
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: string
                type: object
  /countries:
    get:
      tags:
        - Countries
      summary: Get List of all countries
      description: Get List of all countries
      operationId: countries
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      flag:
                        type: string
                      name_common:
                        type: string
                      name_official:
                        type: string
                type: object
      security:
        - api_key_security_example: [ ]
  /keys:
   get:
      tags:
        - Keys
      summary:  Этот api для того чтобы получить Расчетный счет и Номер Кошелка 
      description: Первый Расчетный счет ,второй Номер Кошелка 
      operationId: countries
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      account_number:
                        type: string
                      wallet_number:
                        type: string
                type: object
      security:
        - api_key_security_example: [ ]
components:
  securitySchemes:
    api_key_security_example:
      type: http
      description: A short description for security scheme
      scheme: bearer
      bearerFormat: JWT
security:
  - oauth2_security_example:
      - read
      - write

